language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
addons:
  ssh-known-servers: mattseemon.in
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_6842d37a89d0_key -iv $encrypted_6842d37a89d0_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet _site/ mattseemon@mattseemon.in:~/public_html
  on:
    branch: master